version: '3.7'
services:
  app:
    build: .
    entrypoint: .docker/${ENTRYPOINT_BASH}
    container_name: prisma-api-app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: prisma-api-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
